version: 0.2

phases:
  install:
    commands:
      - echo "Starting Install Phase..."
      
      # Debugging directory and listing contents
      - echo "Current working directory:"
      - pwd
      - echo "Contents of the root directory:"
      - ls -la

      # Backend dependency installation
      - echo "Installing backend dependencies..."
      - if [ -d "/home/ubuntu/MERN-AWSEC2/Backend" ]; then cd /home/ubuntu/MERN-AWSEC2/Backend; else echo "Backend folder not found"; exit 1; fi
      - npm install || { echo "npm install failed for Backend"; exit 1; }
      - cd .. || exit 1

      # Frontend dependency installation
      - echo "Installing frontend dependencies..."
      - echo "Checking Frontend directory..."
      - ls -la /home/ubuntu/MERN-AWSEC2/Frontend || exit 1
      - if [ -d "/home/ubuntu/MERN-AWSEC2/Frontend/my-react-app" ]; then cd /home/ubuntu/MERN-AWSEC2/Frontend/my-react-app; else echo "Frontend/my-react-app folder not found"; exit 1; fi
      - npm install || { echo "npm install failed for Frontend"; exit 1; }

  build:
    commands:
      - echo "Starting Build Phase..."
      - echo "Building frontend..."
      - cd /home/ubuntu/MERN-AWSEC2/Frontend/my-react-app || exit 1
      - npm run build || { echo "npm run build failed for Frontend"; exit 1; }
      - echo "Frontend build completed successfully."

  post_build:
    commands:
      - echo "Post-Build Phase: Build completed successfully."
      - echo "Current directory after build phase:"
      - pwd
      - echo "Listing all contents after build phase:"
      - ls -la

artifacts:
  files:
    - '**/*'



