version: 0.2

phases:
  install:
    commands:
      - echo Installing backend dependencies...
      - cd Backend
      - npm install
      - cd ..
      - echo Installing frontend dependencies...
      - cd Frontend/my-react-app
      - npm install
  build:
    commands:
      - echo Building frontend...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'
