version: 0.2

phases:
  install:
    commands:
      - echo "Installing backend dependencies..."
      - cd Backend || exit 1
      - npm install || exit 1
      - cd .. || exit 1
      - echo "Installing frontend dependencies..."
      - if [ -d "Frontend/my-react-app" ]; then cd Frontend/my-react-app; else echo "Folder not found"; exit 1; fi
      - npm install || exit 1

  build:
    commands:
      - echo "Building frontend..."
      - npm run build || exit 1

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'

