version: 0.2

phases:
  install:
  commands:
    - echo "Checking Backend directory..."
    - ls -la /home/ubuntu/MERN-AWSEC2 || { echo "MERN-AWSEC2 directory not found"; exit 1; }
    - ls -la /home/ubuntu/MERN-AWSEC2/Backend || { echo "Backend folder not found"; exit 1; }
    - echo "Navigating to Backend directory..."
    - cd /home/ubuntu/MERN-AWSEC2/Backend || { echo "Failed to navigate to Backend directory"; exit 1; }
    - echo "Installing backend dependencies..."
    - npm install || { echo "npm install failed for Backend"; exit 1; }
    - echo "Installing frontend dependencies..."
    - if [ -d "/home/ubuntu/MERN-AWSEC2/Frontend/my-react-app" ]; then cd /home/ubuntu/MERN-AWSEC2/Frontend/my-react-app; else echo "Frontend/my-react-app folder not found"; exit 1; fi
    - npm install || { echo "npm install failed for Frontend"; exit 1; }

  build:
    commands:
      - echo "Starting Build Phase..."
      - cd /home/ubuntu/MERN-AWSEC2/Frontend/my-react-app || exit 1
      - npm run build || { echo "npm run build failed for Frontend"; exit 1; }

  post_build:
    commands:
      - echo "Build completed successfully."
      - echo "Listing all contents after build phase:"
      - ls -la

artifacts:
  files:
    - "**/*"
