version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Current working directory: $(pwd)"
      - ls -la
      - echo "Running install.sh script..."
      - cd Backend/scripts
      - chmod +x install.sh
      - ./install.sh

  build:
    commands:
      - echo "Building the frontend..."
      - cd ../../Frontend/my-react-app
      - npm install
      - npm run build

  post_build:
    commands:
      - echo "Running script.sh script..."
      - cd ../../Backend/scripts
      - chmod +x script.sh
      - ./script.sh

artifacts:
  files:
    - '**/*'
