version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Checking my-app directory..."
      - ls -la /home/ubuntu/my-app || { echo "my-app directory not found"; exit 1; }

      - echo "Installing backend dependencies..."
      - cd /home/ubuntu/my-app/Backend && npm install || { echo "npm install failed for Backend"; exit 1; }

      - echo "Installing frontend dependencies..."
      - cd /home/ubuntu/my-app/Frontend/my-react-app && npm install || { echo "npm install failed for Frontend"; exit 1; }

  build:
    commands:
      - echo "Building frontend..."
      - cd /home/ubuntu/my-app/Frontend/my-react-app && npm run build || { echo "npm run build failed"; exit 1; }

  post_build:
    commands:
      - echo "Build completed successfully."
      - echo "Restarting PM2 app..."
      - pm2 restart all

artifacts:
  files:
    - '**/*'
