version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Listing root directory..."
      - ls -la
      - echo "Navigating to Frontend/my-react-app..."
      - ls -la Frontend || { echo "Frontend directory not found"; exit 1; }
      - ls -la Frontend/my-react-app || { echo "my-react-app directory not found"; exit 1; }
      - cd Backend && npm install
      - cd ../Frontend/my-react-app && npm install

  build:
    commands:
      - echo "Building frontend..."
      - cd Frontend/my-react-app && npm run build

  post_build:
    commands:
      - echo "Build completed successfully."
      # Optional: Upload to S3 or SSH to EC2 here

artifacts:
  files:
    - '**/*'
