version: 0.2

frontend:
  phases:
    preBuild:
      commands:
        - cd client && npm install  # Install frontend dependencies
    build:
      commands:
        - cd client && npm run build  # Build the frontend React app
  artifacts:
    baseDirectory: client/dist  # Point to the dist folder for React app
    files:
      - '**/*'

backend:
  phases:
    build:
      commands:
        - cd server && npm install  # Install backend dependencies
        - cd server && npm run build  # Optional: build the backend if needed
  artifacts:
    baseDirectory: server/dist  # Point to the dist folder for the backend (if applicable)
    files:
      - '**/*'
