version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Running install.sh script..."
      - chmod +x scripts/install.sh
      - ./scripts/install.sh

  build:
    commands:
      - echo "Building the frontend..."
      - cd Frontend/my-react-app && npm run build

  post_build:
    commands:
      - echo "Running script.sh script..."
      - chmod +x scripts/script.sh
      - ./scripts/script.sh

artifacts:
  files:
    - '**/*'
