version: 0.2

phases:
  install:
    commands:
      - echo "Starting Install Phase..."
      
      # Debugging directory and listing contents
      - echo "Current working directory:"
      - pwd
      - echo "Contents of the root directory:"
      - ls -la

      # Backend dependency installation
      - echo "Installing backend dependencies..."
      - if [ -d "Backend" ]; then cd Backend; else echo "Backend folder not found"; exit 1; fi
      - npm install || exit 1
      - cd .. || exit 1

      # Frontend dependency installation
      - echo "Installing frontend dependencies..."
      - echo "Checking Frontend directory..."
      - ls -la Frontend || exit 1
      - if [ -d "Frontend/my-react-app" ]; then cd Frontend/my-react-app; else echo "Frontend/my-react-app folder not found"; exit 1; fi
      - npm install || exit 1

  build:
    commands:
      - echo "Starting Build Phase..."
      - echo "Building frontend..."
      - cd Frontend/my-react-app || exit 1 # Ensure we're in the frontend directory
      - npm run build || exit 1
      - echo "Frontend build completed successfully."

  post_build:
    commands:
      - echo "Post-Build Phase: Build completed successfully."
      - echo "Current directory after build phase:"
      - pwd
      - echo "Listing all contents after build phase:"
      - ls -la

artifacts:
  files:
    - '**/*'


