version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing backend dependencies..."
      - cd Backend && npm install

      - echo "Installing frontend dependencies..."
      - cd ../Frontend/my-react-app && npm install

  build:
    commands:
      - echo "Building frontend..."
      - cd Frontend/my-react-app && npm run build

  post_build:
    commands:
      - echo "Build completed successfully."
      # Optional: Upload to S3 or SSH to EC2 here

artifacts:
  files:
    - '**/*'
